# Utilisation d'une image Node.js pour exécuter le pipeline
image: node:lts

# Déploiement GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Déploiement du site vitrine..."
    - npm install  # Installation des dépendances (si nécessaire)
    - npm run build || echo "Pas de script de build défini, passage direct à la publication"
    - mkdir -p public
    - cp -r Inv@teMe_Site/* public/  # Copie le contenu vers le dossier public
  artifacts:
    paths:
      - public  # GitLab Pages déploie uniquement le contenu de 'public'
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH  # Déploiement uniquement sur la branche principale