stages:
  - build
  - test
  - deploy
  - sync

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - sleep 10
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - sleep 5
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

sync-repo:
  stage: sync
  script:
    - apt-get update && apt-get install -y git curl jq
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "CI Bot"
    - git remote set-url origin https://$GITHUB_TOKEN@github.com/GnimGregoireDAO/Invite-Me.git
    - git push --mirror https://$GITHUB_TOKEN@github.com/GnimGregoireDAO/Invite-Me.git

sync-issues:
  stage: sync
  script:
    - apt-get update && apt-get install -y curl jq
    - |
      issues=$(curl -s -H "Private-Token: $GITLAB_TOKEN" "https://git.dti.crosemont.quebec/api/v4/projects/7773/issues")
      echo "------ Issues response ------"
      echo "$issues"
      echo "----------------------------"
      echo "$issues" | jq -c '.[]' | while read -r issue; do
        title=$(echo "$issue" | jq -r '.title')
        body=$(echo "$issue" | jq -r '.description')
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"title\": \"$title\", \"body\": \"$body\"}" \
          "https://api.github.com/repos/GnimGregoireDAO/Invite-Me/issues"
      done
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GITHUB_TOKEN: $GITHUB_TOKEN

sync-tags:
  stage: sync
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "CI Bot"
    - git push --tags https://$GITHUB_TOKEN@github.com/GnimGregoireDAO/Invite-Me.git
    - git push --all https://$GITHUB_TOKEN@github.com/GnimGregoireDAO/Invite-Me.git