stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

trigger-github-actions:
  stage: deploy
  script:
    - apt-get update && apt-get install -y curl  # 👈 Installation de curl
    - |
      curl -X POST -H "Authorization: token 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" \
           -H "Accept: application/vnd.github.v3+json" \
           -d '{"ref":"main"}' \
           "https://api.github.com/repos/GnimGregoireDAO/Invite-Me/actions/workflows/164152526/dispatches"